import { AccountClass, AccountType } from '@prisma/client';
import type { CoaTemplate } from '../coa.types';

export const agricultureTemplate: CoaTemplate = {
  name: 'Agriculture',
  description: 'Chart of accounts for farming, greenhouse, and agri-business operations',
  industry: 'Agriculture',
  accounts: [
    // ─── ROOT NODES ──────────────────────────────────────────────────────────
    { code: '100000', name: 'Assets', class: AccountClass.ASSET, type: AccountType.OTHER, parentCode: null, level: 0, subClass: 'Root' },
    { code: '200000', name: 'Liabilities', class: AccountClass.LIABILITY, type: AccountType.OTHER, parentCode: null, level: 0, subClass: 'Root' },
    { code: '300000', name: 'Equity', class: AccountClass.EQUITY, type: AccountType.EQUITY_ACCOUNT, parentCode: null, level: 0, subClass: 'Root' },
    { code: '400000', name: 'Income', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: null, level: 0, subClass: 'Root' },
    { code: '500000', name: 'Cost of Sales', class: AccountClass.EXPENSE, type: AccountType.COST_OF_SALES, parentCode: null, level: 0, subClass: 'Root' },
    { code: '600000', name: 'General & Admin Expenses', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: null, level: 0, subClass: 'Root' },
    { code: '700000', name: 'Finance Costs & Adjustments', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: null, level: 0, subClass: 'Root' },

    // ─── ASSETS: NON-CURRENT ─────────────────────────────────────────────────
    { code: '110000', name: 'Property, Plant and Equipment', class: AccountClass.ASSET, type: AccountType.FIXED_ASSET, parentCode: '100000', level: 1, subClass: 'Non-current Asset' },

    { code: '110100', name: 'Building', class: AccountClass.ASSET, type: AccountType.FIXED_ASSET, parentCode: '110000', level: 2, subClass: 'Non-current Asset' },
    { code: '110110', name: 'Building - Cost', class: AccountClass.ASSET, type: AccountType.FIXED_ASSET, parentCode: '110100', level: 3, subClass: 'Non-current Asset' },
    { code: '110120', name: 'Building - Accumulated Depreciation', class: AccountClass.ASSET, type: AccountType.FIXED_ASSET, parentCode: '110100', level: 3, subClass: 'Non-current Asset' },

    { code: '110200', name: 'Motor Vehicle', class: AccountClass.ASSET, type: AccountType.FIXED_ASSET, parentCode: '110000', level: 2, subClass: 'Non-current Asset' },
    { code: '110210', name: 'Motor Vehicle - Cost', class: AccountClass.ASSET, type: AccountType.FIXED_ASSET, parentCode: '110200', level: 3, subClass: 'Non-current Asset' },
    { code: '110220', name: 'Motor Vehicle - Accumulated Depreciation', class: AccountClass.ASSET, type: AccountType.FIXED_ASSET, parentCode: '110200', level: 3, subClass: 'Non-current Asset' },

    { code: '110300', name: 'Farm Equipment', class: AccountClass.ASSET, type: AccountType.FIXED_ASSET, parentCode: '110000', level: 2, subClass: 'Non-current Asset' },
    { code: '110310', name: 'Farm Equipment - Cost', class: AccountClass.ASSET, type: AccountType.FIXED_ASSET, parentCode: '110300', level: 3, subClass: 'Non-current Asset' },
    { code: '110320', name: 'Farm Equipment - Accumulated Depreciation', class: AccountClass.ASSET, type: AccountType.FIXED_ASSET, parentCode: '110300', level: 3, subClass: 'Non-current Asset' },

    { code: '110400', name: 'Furniture & Fittings', class: AccountClass.ASSET, type: AccountType.FIXED_ASSET, parentCode: '110000', level: 2, subClass: 'Non-current Asset' },
    { code: '110410', name: 'Furniture & Fittings - Cost', class: AccountClass.ASSET, type: AccountType.FIXED_ASSET, parentCode: '110400', level: 3, subClass: 'Non-current Asset' },
    { code: '110420', name: 'Furniture & Fittings - Accumulated Depreciation', class: AccountClass.ASSET, type: AccountType.FIXED_ASSET, parentCode: '110400', level: 3, subClass: 'Non-current Asset' },

    { code: '110500', name: 'Green House', class: AccountClass.ASSET, type: AccountType.FIXED_ASSET, parentCode: '110000', level: 2, subClass: 'Non-current Asset' },
    { code: '110510', name: 'Green House - Cost', class: AccountClass.ASSET, type: AccountType.FIXED_ASSET, parentCode: '110500', level: 3, subClass: 'Non-current Asset' },
    { code: '110520', name: 'Green House - Accumulated Depreciation', class: AccountClass.ASSET, type: AccountType.FIXED_ASSET, parentCode: '110500', level: 3, subClass: 'Non-current Asset' },

    { code: '110600', name: 'Computer Hardware', class: AccountClass.ASSET, type: AccountType.FIXED_ASSET, parentCode: '110000', level: 2, subClass: 'Non-current Asset' },
    { code: '110610', name: 'Computer Hardware - Cost', class: AccountClass.ASSET, type: AccountType.FIXED_ASSET, parentCode: '110600', level: 3, subClass: 'Non-current Asset' },
    { code: '110620', name: 'Computer Hardware - Accumulated Depreciation', class: AccountClass.ASSET, type: AccountType.FIXED_ASSET, parentCode: '110600', level: 3, subClass: 'Non-current Asset' },

    { code: '110700', name: 'Loose Tools', class: AccountClass.ASSET, type: AccountType.FIXED_ASSET, parentCode: '110000', level: 2, subClass: 'Non-current Asset' },
    { code: '100710', name: 'Loose Tools - Cost', class: AccountClass.ASSET, type: AccountType.FIXED_ASSET, parentCode: '110700', level: 3, subClass: 'Non-current Asset' },
    { code: '110720', name: 'Loose Tools - Accumulated Depreciation', class: AccountClass.ASSET, type: AccountType.FIXED_ASSET, parentCode: '110700', level: 3, subClass: 'Non-current Asset' },

    { code: '110800', name: 'Farm Land', class: AccountClass.ASSET, type: AccountType.FIXED_ASSET, parentCode: '110000', level: 2, subClass: 'Non-current Asset' },
    { code: '110810', name: 'Farm Land - Cost', class: AccountClass.ASSET, type: AccountType.FIXED_ASSET, parentCode: '110800', level: 3, subClass: 'Non-current Asset' },
    { code: '110820', name: 'Farm Land - Accumulated Depreciation', class: AccountClass.ASSET, type: AccountType.FIXED_ASSET, parentCode: '110800', level: 3, subClass: 'Non-current Asset', description: 'Note: IAS 16 prohibits depreciation of land. Retained per client preference.' },

    { code: '110900', name: 'Farm Plant & Machinery', class: AccountClass.ASSET, type: AccountType.FIXED_ASSET, parentCode: '110000', level: 2, subClass: 'Non-current Asset' },
    { code: '110910', name: 'Farm Plant & Machinery - Cost', class: AccountClass.ASSET, type: AccountType.FIXED_ASSET, parentCode: '110900', level: 3, subClass: 'Non-current Asset' },
    { code: '110920', name: 'Farm Plant & Machinery - Accumulated Depreciation', class: AccountClass.ASSET, type: AccountType.FIXED_ASSET, parentCode: '110900', level: 3, subClass: 'Non-current Asset' },

    { code: '120000', name: 'Control / Contra Accounts', class: AccountClass.ASSET, type: AccountType.OTHER, parentCode: '100000', level: 1, subClass: 'Non-current Asset', isControlAccount: true },
    { code: '120100', name: 'Fixed Asset Control Account', class: AccountClass.ASSET, type: AccountType.FIXED_ASSET, parentCode: '120000', level: 2, subClass: 'Non-current Asset', isControlAccount: true },

    { code: '130000', name: 'Intangible Assets', class: AccountClass.ASSET, type: AccountType.INTANGIBLE, parentCode: '100000', level: 1, subClass: 'Non-current Asset' },
    { code: '130100', name: 'Computer Software', class: AccountClass.ASSET, type: AccountType.INTANGIBLE, parentCode: '130000', level: 2, subClass: 'Non-current Asset' },
    { code: '130110', name: 'Computer Software - Cost', class: AccountClass.ASSET, type: AccountType.INTANGIBLE, parentCode: '130100', level: 3, subClass: 'Non-current Asset' },
    { code: '130120', name: 'Computer Software - Amortisation', class: AccountClass.ASSET, type: AccountType.INTANGIBLE, parentCode: '130100', level: 3, subClass: 'Non-current Asset' },

    { code: '140000', name: 'Other PPE', class: AccountClass.ASSET, type: AccountType.FIXED_ASSET, parentCode: '100000', level: 1, subClass: 'Non-current Asset' },

    // ─── ASSETS: CURRENT ─────────────────────────────────────────────────────
    { code: '170000', name: 'Current Assets', class: AccountClass.ASSET, type: AccountType.OTHER, parentCode: '100000', level: 1, subClass: 'Current Asset' },

    { code: '170100', name: 'Bank', class: AccountClass.ASSET, type: AccountType.BANK, parentCode: '170000', level: 2, subClass: 'Current Asset' },
    { code: '170110', name: 'Commercial Bank - Cedi Account', class: AccountClass.ASSET, type: AccountType.BANK, parentCode: '170100', level: 3, subClass: 'Current Asset', isBankAccount: true },
    { code: '170120', name: 'Commercial Bank - Dollar Account', class: AccountClass.ASSET, type: AccountType.BANK, parentCode: '170100', level: 3, subClass: 'Current Asset', isBankAccount: true, currency: 'USD' },

    { code: '170200', name: 'Cash', class: AccountClass.ASSET, type: AccountType.CASH, parentCode: '170000', level: 2, subClass: 'Current Asset' },
    { code: '170210', name: 'Cash in Hand', class: AccountClass.ASSET, type: AccountType.CASH, parentCode: '170200', level: 3, subClass: 'Current Asset' },
    { code: '170220', name: 'Mobile Money - MoMo 1', class: AccountClass.ASSET, type: AccountType.CASH, parentCode: '170200', level: 3, subClass: 'Current Asset' },
    { code: '170230', name: 'Mobile Money - MoMo 2', class: AccountClass.ASSET, type: AccountType.CASH, parentCode: '170200', level: 3, subClass: 'Current Asset' },

    { code: '170300', name: 'Inventory Control', class: AccountClass.ASSET, type: AccountType.INVENTORY, parentCode: '170000', level: 2, subClass: 'Current Asset', isControlAccount: true },
    { code: '170400', name: 'Receivables Control', class: AccountClass.ASSET, type: AccountType.RECEIVABLE, parentCode: '170000', level: 2, subClass: 'Current Asset', isControlAccount: true },
    { code: '170500', name: 'Input VAT', class: AccountClass.ASSET, type: AccountType.TAX_RECEIVABLE, parentCode: '170000', level: 2, subClass: 'Current Asset' },
    { code: '170600', name: 'Prepaid Expenses', class: AccountClass.ASSET, type: AccountType.OTHER, parentCode: '170000', level: 2, subClass: 'Current Asset' },
    { code: '170700', name: 'Deferred Tax Asset', class: AccountClass.ASSET, type: AccountType.OTHER, parentCode: '170000', level: 2, subClass: 'Current Asset' },

    { code: '190000', name: 'Clearing / Contra Accounts', class: AccountClass.ASSET, type: AccountType.OTHER, parentCode: '100000', level: 1, subClass: 'Clearing', isControlAccount: true },
    { code: '190100', name: 'Clearing / Contra Account', class: AccountClass.ASSET, type: AccountType.OTHER, parentCode: '190000', level: 2, subClass: 'Clearing', isControlAccount: true },

    // ─── LIABILITIES ─────────────────────────────────────────────────────────
    { code: '210000', name: 'Non-Current Liabilities', class: AccountClass.LIABILITY, type: AccountType.PAYABLE, parentCode: '200000', level: 1, subClass: 'Non-Current Liability' },
    { code: '210100', name: 'Long-term Loans', class: AccountClass.LIABILITY, type: AccountType.PAYABLE, parentCode: '210000', level: 2, subClass: 'Non-Current Liability' },
    { code: '210200', name: 'Mortgage / Property Loan', class: AccountClass.LIABILITY, type: AccountType.PAYABLE, parentCode: '210000', level: 2, subClass: 'Non-Current Liability' },

    { code: '220000', name: 'Current Liabilities', class: AccountClass.LIABILITY, type: AccountType.PAYABLE, parentCode: '200000', level: 1, subClass: 'Current Liability' },
    { code: '220100', name: 'Accounts Payables', class: AccountClass.LIABILITY, type: AccountType.PAYABLE, parentCode: '220000', level: 2, subClass: 'Current Liability', isControlAccount: true },
    { code: '220200', name: 'Rent Accrued', class: AccountClass.LIABILITY, type: AccountType.PAYABLE, parentCode: '220000', level: 2, subClass: 'Current Liability' },
    { code: '220300', name: 'GRA - PAYE', class: AccountClass.LIABILITY, type: AccountType.TAX_PAYABLE, parentCode: '220000', level: 2, subClass: 'Current Liability' },
    { code: '220400', name: 'SSNIT', class: AccountClass.LIABILITY, type: AccountType.PAYABLE, parentCode: '220000', level: 2, subClass: 'Current Liability' },
    { code: '220500', name: 'Withholding Tax Payable', class: AccountClass.LIABILITY, type: AccountType.TAX_PAYABLE, parentCode: '220000', level: 2, subClass: 'Current Liability' },
    { code: '220600', name: 'Output VAT', class: AccountClass.LIABILITY, type: AccountType.TAX_PAYABLE, parentCode: '220000', level: 2, subClass: 'Current Liability' },

    { code: '230000', name: 'Provisions', class: AccountClass.LIABILITY, type: AccountType.OTHER, parentCode: '200000', level: 1, subClass: 'Current Liability' },
    { code: '230100', name: 'Provision for Damaged Inventory', class: AccountClass.LIABILITY, type: AccountType.OTHER, parentCode: '230000', level: 2, subClass: 'Current Liability' },

    // ─── EQUITY ──────────────────────────────────────────────────────────────
    { code: '300100', name: 'Stated Capital', class: AccountClass.EQUITY, type: AccountType.EQUITY_ACCOUNT, parentCode: '300000', level: 1, subClass: 'Equity' },
    { code: '300200', name: 'Retained Earnings', class: AccountClass.EQUITY, type: AccountType.EQUITY_ACCOUNT, parentCode: '300000', level: 1, subClass: 'Equity' },

    // ─── REVENUE ─────────────────────────────────────────────────────────────
    { code: '410000', name: 'Sales Revenue', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '400000', level: 1, subClass: 'Revenue' },
    { code: '410010', name: 'Parsley', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410015', name: 'Basil', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410020', name: 'Cucumber', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410025', name: 'Cucumber G2', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410030', name: 'Thyme', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410035', name: 'Aubergine', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410040', name: 'Coriander', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410045', name: 'Mint', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410050', name: 'Bakleh', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410055', name: 'Chard', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410060', name: 'Wild Cucumber', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410065', name: 'Eggplant Rosa', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410070', name: 'Sweet Corn', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410075', name: 'Rocca', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410080', name: 'Arugula', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410085', name: 'Green Mullow', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410090', name: 'Basil Pot', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410095', name: 'Dandelion', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410100', name: 'Red Radish', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410105', name: 'Green Chilli Pepper', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410110', name: 'Vine Leaves', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410115', name: 'Hindbeh', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410120', name: 'Lebanese Thyme', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410125', name: 'Organic Cucumber', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410130', name: 'Curly Kale', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410135', name: 'Lebanese Cucumber', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410140', name: 'Vine Grape', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410145', name: 'Yellow Melon', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410150', name: 'Wild Thyme', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410155', name: 'Ghanaian Lettuce', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410160', name: 'Red Chilli Pepper', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410165', name: 'Zucchini', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410170', name: 'Lebanese Lettuce', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410175', name: 'Sweet Cucumber', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410180', name: 'Squash', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410185', name: 'Rocca Pot', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410190', name: 'Lebanese Cucumber Mini (Baladi)', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410195', name: 'Aubergine Grade 2', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410200', name: 'Aubergine Black Beauty', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410205', name: 'Green Bell Pepper Large', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410210', name: 'Dry Mullow', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410215', name: 'Arugula KG VVF', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410220', name: 'Wild Cucumber Large KG VVF', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410225', name: 'Cucumber Local KG VVF', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410230', name: 'Wild Leaves', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410235', name: 'Sweet Corn Pack 2Pcs VVF', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410240', name: 'Sweet Corn Peeled Pack VVF', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410245', name: 'Baby Spinach 125G VVF', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410250', name: 'Tomato', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410255', name: 'Dill Bundle 100G VVF', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410260', name: 'Beef Tomato 1KG', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410265', name: 'Cherry Tomato on the Vine Bicolor 200G', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410270', name: 'Cherry Tomato 200G', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410275', name: 'Cherry Tomato Brown 200G VVF', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410280', name: 'Cherry Tomato Yellow 200G VVF', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410285', name: 'Beef Tomato 500G', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410290', name: 'Cherry Tomato 1KG', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410295', name: 'Romaine Lettuce', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },
    { code: '410300', name: 'Romaine Lettuce Pack VVF', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 2, subClass: 'Revenue' },

    { code: '420000', name: 'Sales Returns', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '400000', level: 1, subClass: 'Revenue', description: 'Contra-revenue account for sales returns and allowances' },
    { code: '490000', name: 'Other Income', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '400000', level: 1, subClass: 'Other Income' },

    // ─── COST OF SALES ───────────────────────────────────────────────────────
    { code: '510000', name: 'Direct Farming Cost', class: AccountClass.EXPENSE, type: AccountType.COST_OF_SALES, parentCode: '500000', level: 1, subClass: 'Cost of Sales' },

    { code: '510100', name: 'Seeds', class: AccountClass.EXPENSE, type: AccountType.COST_OF_SALES, parentCode: '510000', level: 2, subClass: 'Cost of Sales' },
    { code: '510110', name: 'Seeds - Cost Local', class: AccountClass.EXPENSE, type: AccountType.COST_OF_SALES, parentCode: '510100', level: 3, subClass: 'Cost of Sales' },
    { code: '510115', name: 'Seeds - Cost Foreign', class: AccountClass.EXPENSE, type: AccountType.COST_OF_SALES, parentCode: '510100', level: 3, subClass: 'Cost of Sales' },
    { code: '510120', name: 'Seeds - Import Duties', class: AccountClass.EXPENSE, type: AccountType.COST_OF_SALES, parentCode: '510100', level: 3, subClass: 'Cost of Sales' },
    { code: '510125', name: 'Seeds - Freight', class: AccountClass.EXPENSE, type: AccountType.COST_OF_SALES, parentCode: '510100', level: 3, subClass: 'Cost of Sales' },
    { code: '510130', name: 'Seeds - Other Cost', class: AccountClass.EXPENSE, type: AccountType.COST_OF_SALES, parentCode: '510100', level: 3, subClass: 'Cost of Sales' },

    { code: '510200', name: 'Irrigation and Pipes', class: AccountClass.EXPENSE, type: AccountType.COST_OF_SALES, parentCode: '510000', level: 2, subClass: 'Cost of Sales' },
    { code: '510210', name: 'Pipe Materials', class: AccountClass.EXPENSE, type: AccountType.COST_OF_SALES, parentCode: '510200', level: 3, subClass: 'Cost of Sales' },
    { code: '510215', name: 'Pipe Connectors', class: AccountClass.EXPENSE, type: AccountType.COST_OF_SALES, parentCode: '510200', level: 3, subClass: 'Cost of Sales' },

    { code: '510300', name: 'Fertilizer and Chemicals', class: AccountClass.EXPENSE, type: AccountType.COST_OF_SALES, parentCode: '510000', level: 2, subClass: 'Cost of Sales' },
    { code: '510310', name: 'Fertilizer', class: AccountClass.EXPENSE, type: AccountType.COST_OF_SALES, parentCode: '510300', level: 3, subClass: 'Cost of Sales' },
    { code: '510315', name: 'Manure', class: AccountClass.EXPENSE, type: AccountType.COST_OF_SALES, parentCode: '510300', level: 3, subClass: 'Cost of Sales' },
    { code: '510320', name: 'Weedicide', class: AccountClass.EXPENSE, type: AccountType.COST_OF_SALES, parentCode: '510300', level: 3, subClass: 'Cost of Sales' },
    { code: '510325', name: 'Pesticide', class: AccountClass.EXPENSE, type: AccountType.COST_OF_SALES, parentCode: '510300', level: 3, subClass: 'Cost of Sales' },
    { code: '510330', name: 'Other Chemicals', class: AccountClass.EXPENSE, type: AccountType.COST_OF_SALES, parentCode: '510300', level: 3, subClass: 'Cost of Sales' },

    { code: '510400', name: 'Soil', class: AccountClass.EXPENSE, type: AccountType.COST_OF_SALES, parentCode: '510000', level: 2, subClass: 'Cost of Sales' },
    { code: '510410', name: 'Treated Soil', class: AccountClass.EXPENSE, type: AccountType.COST_OF_SALES, parentCode: '510400', level: 3, subClass: 'Cost of Sales' },

    { code: '510500', name: 'Water - Farm', class: AccountClass.EXPENSE, type: AccountType.COST_OF_SALES, parentCode: '510000', level: 2, subClass: 'Cost of Sales' },
    { code: '510600', name: 'Rubber', class: AccountClass.EXPENSE, type: AccountType.COST_OF_SALES, parentCode: '510000', level: 2, subClass: 'Cost of Sales' },

    // ─── EXPENSES: EMPLOYEE COSTS ────────────────────────────────────────────
    { code: '610000', name: 'Employee Related Costs', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '600000', level: 1, subClass: 'Operating Expense' },
    { code: '610100', name: 'Basic Salaries', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '610000', level: 2, subClass: 'Operating Expense' },
    { code: '610200', name: 'Bonus', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '610000', level: 2, subClass: 'Operating Expense' },
    { code: '610310', name: 'Cash Allowance', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '610000', level: 2, subClass: 'Operating Expense' },
    { code: '610320', name: 'Overtime', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '610000', level: 2, subClass: 'Operating Expense' },
    { code: '610400', name: 'Employer SSNIT', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '610000', level: 2, subClass: 'Operating Expense' },
    { code: '610500', name: 'Employer Pension Fund', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '610000', level: 2, subClass: 'Operating Expense' },
    { code: '610600', name: 'Medical & Health Cost', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '610000', level: 2, subClass: 'Operating Expense' },
    { code: '610700', name: 'Staff Feeding', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '610000', level: 2, subClass: 'Operating Expense' },
    { code: '610800', name: 'Staff Transport', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '610000', level: 2, subClass: 'Operating Expense' },
    { code: '610900', name: 'Other Staff Cost', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '610000', level: 2, subClass: 'Operating Expense' },
    { code: '611000', name: 'Statutory - GRA', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '610000', level: 2, subClass: 'Operating Expense' },

    // ─── EXPENSES: UTILITIES ─────────────────────────────────────────────────
    { code: '620000', name: 'Utilities', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '600000', level: 1, subClass: 'Operating Expense' },
    { code: '620100', name: 'Electricity', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '620000', level: 2, subClass: 'Operating Expense' },
    { code: '620200', name: 'Water - Domestic', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '620000', level: 2, subClass: 'Operating Expense' },
    { code: '620300', name: 'Fuel - Gas', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '620000', level: 2, subClass: 'Operating Expense' },
    { code: '620400', name: 'Fuel - Diesel', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '620000', level: 2, subClass: 'Operating Expense' },
    { code: '620500', name: 'Fuel - Petrol', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '620000', level: 2, subClass: 'Operating Expense' },

    // ─── EXPENSES: REPAIRS & MAINTENANCE ─────────────────────────────────────
    { code: '630000', name: 'Repairs and Maintenance', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '600000', level: 1, subClass: 'Operating Expense' },
    { code: '630100', name: 'Tractor Repairs', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '630000', level: 2, subClass: 'Operating Expense' },
    { code: '630110', name: 'Tractor Repairs - Parts', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '630100', level: 3, subClass: 'Operating Expense' },
    { code: '630115', name: 'Tractor Repairs - Service Cost', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '630100', level: 3, subClass: 'Operating Expense' },
    { code: '630120', name: 'Tractor Repairs - Other', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '630100', level: 3, subClass: 'Operating Expense' },
    { code: '630200', name: 'Delivery Van Repairs', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '630000', level: 2, subClass: 'Operating Expense' },
    { code: '630210', name: 'Delivery Van Repairs - Parts', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '630200', level: 3, subClass: 'Operating Expense' },
    { code: '630215', name: 'Delivery Van Repairs - Service Cost', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '630200', level: 3, subClass: 'Operating Expense' },
    { code: '630220', name: 'Delivery Van Repairs - Other', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '630200', level: 3, subClass: 'Operating Expense' },
    { code: '630300', name: 'Building and Structures', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '630000', level: 2, subClass: 'Operating Expense' },
    { code: '630325', name: 'Building Repairs - Parts & Material', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '630300', level: 3, subClass: 'Operating Expense' },
    { code: '630315', name: 'Building Repairs - Service Cost', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '630300', level: 3, subClass: 'Operating Expense' },
    { code: '630320', name: 'Building Repairs - Other', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '630300', level: 3, subClass: 'Operating Expense' },
    { code: '630400', name: 'Green House Repairs', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '630000', level: 2, subClass: 'Operating Expense' },
    { code: '630410', name: 'Green House Repairs - Parts & Material', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '630400', level: 3, subClass: 'Operating Expense' },
    { code: '630415', name: 'Green House Repairs - Service Cost', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '630400', level: 3, subClass: 'Operating Expense' },
    { code: '630420', name: 'Green House Repairs - Other', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '630400', level: 3, subClass: 'Operating Expense' },
    { code: '630500', name: 'Container Repairs', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '630000', level: 2, subClass: 'Operating Expense' },
    { code: '630510', name: 'Container Repairs - Parts & Material', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '630500', level: 3, subClass: 'Operating Expense' },
    { code: '630515', name: 'Container Repairs - Service Cost', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '630500', level: 3, subClass: 'Operating Expense' },
    { code: '630520', name: 'Container Repairs - Other', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '630500', level: 3, subClass: 'Operating Expense' },
    { code: '630600', name: 'Ops Vehicle Repairs', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '630000', level: 2, subClass: 'Operating Expense' },
    { code: '630610', name: 'Ops Vehicle Repairs - Parts & Material', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '630600', level: 3, subClass: 'Operating Expense' },
    { code: '630615', name: 'Ops Vehicle Repairs - Service Cost', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '630600', level: 3, subClass: 'Operating Expense' },
    { code: '630620', name: 'Ops Vehicle Repairs - Other', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '630600', level: 3, subClass: 'Operating Expense' },
    { code: '630700', name: 'Farm Equipment Repairs', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '630000', level: 2, subClass: 'Operating Expense' },
    { code: '630710', name: 'Farm Equipment Repairs - Water Pump', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '630700', level: 3, subClass: 'Operating Expense' },
    { code: '630715', name: 'Farm Equipment Repairs - Genset', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '630700', level: 3, subClass: 'Operating Expense' },
    { code: '630720', name: 'Farm Equipment Repairs - Farm Tools', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '630700', level: 3, subClass: 'Operating Expense' },
    { code: '630725', name: 'Farm Equipment Repairs - Other', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '630700', level: 3, subClass: 'Operating Expense' },
    { code: '630800', name: 'Borehole Maintenance', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '630000', level: 2, subClass: 'Operating Expense' },
    { code: '630900', name: 'General Farm Repairs', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '630000', level: 2, subClass: 'Operating Expense' },

    // ─── EXPENSES: PACKAGING ─────────────────────────────────────────────────
    { code: '640000', name: 'Packaging Materials', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '600000', level: 1, subClass: 'Operating Expense' },
    { code: '640100', name: 'Packaging Rubber', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '640000', level: 2, subClass: 'Operating Expense' },
    { code: '640200', name: 'Packaging Rubber Tie/Band', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '640000', level: 2, subClass: 'Operating Expense' },
    { code: '640300', name: 'Packaging Container Packs', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '640000', level: 2, subClass: 'Operating Expense' },
    { code: '640400', name: 'Packaging Boxes', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '640000', level: 2, subClass: 'Operating Expense' },
    { code: '640500', name: 'Packaging Crates', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '640000', level: 2, subClass: 'Operating Expense' },
    { code: '640600', name: 'Packaging Cling Film', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '640000', level: 2, subClass: 'Operating Expense' },
    { code: '640700', name: 'Packaging Stickers', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '640000', level: 2, subClass: 'Operating Expense' },
    { code: '640800', name: 'Packaging Paper', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '640000', level: 2, subClass: 'Operating Expense' },
    { code: '640900', name: 'Packaging Cost - Other', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '640000', level: 2, subClass: 'Operating Expense' },

    // ─── EXPENSES: STATUTORY ─────────────────────────────────────────────────
    { code: '650000', name: 'Statutory and Regulatory Costs', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '600000', level: 1, subClass: 'Operating Expense' },
    { code: '650100', name: 'EPA Related Costs', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '650000', level: 2, subClass: 'Operating Expense' },
    { code: '650110', name: 'EPA - Permit', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '650100', level: 3, subClass: 'Operating Expense' },
    { code: '650115', name: 'EPA - Inspection Fees', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '650100', level: 3, subClass: 'Operating Expense' },
    { code: '650200', name: 'Operating Permit', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '650000', level: 2, subClass: 'Operating Expense' },
    { code: '650300', name: 'ORC Related Costs', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '650000', level: 2, subClass: 'Operating Expense' },
    { code: '650400', name: 'District Assembly Costs', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '650000', level: 2, subClass: 'Operating Expense' },
    { code: '650500', name: 'DVLA - Roadworthy & Other Cost', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '650000', level: 2, subClass: 'Operating Expense' },
    { code: '650600', name: 'Insurance - Vehicle and Equipment', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '650000', level: 2, subClass: 'Operating Expense' },

    // ─── EXPENSES: FARM OPERATIONAL ──────────────────────────────────────────
    { code: '660000', name: 'Farm Operational Expenses', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '600000', level: 1, subClass: 'Operating Expense' },
    { code: '660100', name: 'Farm Tools & Minor Equipment', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '660000', level: 2, subClass: 'Operating Expense' },
    { code: '660200', name: 'Safety Items & Personal Protective Equipment', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '660000', level: 2, subClass: 'Operating Expense' },
    { code: '660210', name: 'Safety Items - Boots', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '660200', level: 3, subClass: 'Operating Expense' },
    { code: '660215', name: 'Safety Items - Coveralls', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '660200', level: 3, subClass: 'Operating Expense' },
    { code: '660220', name: 'Safety Items - Gloves', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '660200', level: 3, subClass: 'Operating Expense' },
    { code: '660225', name: 'Safety Items - Goggles', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '660200', level: 3, subClass: 'Operating Expense' },
    { code: '660230', name: 'Safety Items - Nose Masks', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '660200', level: 3, subClass: 'Operating Expense' },
    { code: '660235', name: 'Safety Items - Helmet', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '660200', level: 3, subClass: 'Operating Expense' },
    { code: '660240', name: 'Safety Items - Other', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '660200', level: 3, subClass: 'Operating Expense' },
    { code: '660245', name: 'Safety Signs', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '660200', level: 3, subClass: 'Operating Expense' },
    { code: '660300', name: 'Transport & Carriage Inwards - Farm', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '660000', level: 2, subClass: 'Operating Expense' },
    { code: '660400', name: 'Cleaning & Sanitation', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '660000', level: 2, subClass: 'Operating Expense' },
    { code: '660500', name: 'Farm Labour Hire', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '660000', level: 2, subClass: 'Operating Expense' },
    { code: '660600', name: 'General Consumables', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '660000', level: 2, subClass: 'Operating Expense' },
    { code: '660610', name: 'Oil', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '660600', level: 3, subClass: 'Operating Expense' },
    { code: '660615', name: 'Grease', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '660600', level: 3, subClass: 'Operating Expense' },
    { code: '660620', name: 'Office Stationery - Farm Office', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '660600', level: 3, subClass: 'Operating Expense' },
    { code: '660625', name: 'General Consumables - Other', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '660600', level: 3, subClass: 'Operating Expense' },
    { code: '660700', name: 'Farm Consultants', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '660000', level: 2, subClass: 'Operating Expense' },
    { code: '660710', name: 'Consultant - Soil', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '660700', level: 3, subClass: 'Operating Expense' },
    { code: '660715', name: 'Consultant - Plant Disease', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '660700', level: 3, subClass: 'Operating Expense' },
    { code: '660720', name: 'Consultant - Mechanical & Engineering', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '660700', level: 3, subClass: 'Operating Expense' },
    { code: '660725', name: 'Consultant - Quality & Safety', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '660700', level: 3, subClass: 'Operating Expense' },
    { code: '660730', name: 'Consultant - Laboratory Analysis', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '660700', level: 3, subClass: 'Operating Expense' },
    { code: '660735', name: 'Consultant - Environment', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '660700', level: 3, subClass: 'Operating Expense' },
    { code: '660740', name: 'Consultant - General', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '660700', level: 3, subClass: 'Operating Expense' },
    { code: '660745', name: 'Consultant - Accounting & Finance', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '660700', level: 3, subClass: 'Operating Expense' },
    { code: '660800', name: 'Farm Equipment Hire', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '660000', level: 2, subClass: 'Operating Expense' },

    // ─── EXPENSES: FARM ADMINISTRATION ───────────────────────────────────────
    { code: '670000', name: 'Farm Administration Expenses', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '600000', level: 1, subClass: 'Administrative Expense' },
    { code: '670100', name: 'IT, Software & Computer Expenses', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '670000', level: 2, subClass: 'Administrative Expense' },
    { code: '670110', name: 'Software Cost', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '670100', level: 3, subClass: 'Administrative Expense' },
    { code: '670115', name: 'Software Maintenance', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '670100', level: 3, subClass: 'Administrative Expense' },
    { code: '670120', name: 'Toner', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '670100', level: 3, subClass: 'Administrative Expense' },
    { code: '670125', name: 'Courier and Delivery', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '670100', level: 3, subClass: 'Administrative Expense' },
    { code: '670130', name: 'Computer Accessories', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '670100', level: 3, subClass: 'Administrative Expense' },

    // ─── EXPENSES: CORPORATE ─────────────────────────────────────────────────
    { code: '680000', name: 'Farm Corporate Related Costs', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '600000', level: 1, subClass: 'Administrative Expense' },
    { code: '680100', name: 'Transport & Travel - Corporate', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '680000', level: 2, subClass: 'Administrative Expense' },
    { code: '680110', name: 'Corporate - Lunch', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '680100', level: 3, subClass: 'Administrative Expense' },
    { code: '680115', name: 'Corporate Travel', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '680100', level: 3, subClass: 'Administrative Expense' },
    { code: '680120', name: 'Corporate - Hotel & Accommodation', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '680100', level: 3, subClass: 'Administrative Expense' },
    { code: '680125', name: 'Corporate - Director Expense', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '680100', level: 3, subClass: 'Administrative Expense' },
    { code: '680200', name: 'Internet and Communication', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '680000', level: 2, subClass: 'Administrative Expense' },
    { code: '680210', name: 'Internet and Data', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '680200', level: 3, subClass: 'Administrative Expense' },
    { code: '680215', name: 'Telephone', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '680200', level: 3, subClass: 'Administrative Expense' },
    { code: '680300', name: 'Office Rental', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '680000', level: 2, subClass: 'Administrative Expense' },
    { code: '680400', name: 'Newspaper, Magazines and Periodicals', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '680000', level: 2, subClass: 'Administrative Expense' },

    // ─── EXPENSES: SELLING & DISTRIBUTION ────────────────────────────────────
    { code: '690000', name: 'Selling, Distribution and Marketing', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '600000', level: 1, subClass: 'Distribution Cost' },
    { code: '690100', name: 'Social Media and Website Management', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '690000', level: 2, subClass: 'Distribution Cost' },
    { code: '690200', name: 'Promotions and Public Relations', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '690000', level: 2, subClass: 'Distribution Cost' },
    { code: '690300', name: 'Sponsorships', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '690000', level: 2, subClass: 'Distribution Cost' },
    { code: '690400', name: 'Discounts Allowed', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '690000', level: 2, subClass: 'Distribution Cost' },

    // ─── DEPRECIATION & AMORTISATION ─────────────────────────────────────────
    { code: '710000', name: 'Depreciation', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '700000', level: 1, subClass: 'Depreciation & Amortisation' },
    { code: '710100', name: 'Building - Depreciation', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '710000', level: 2, subClass: 'Depreciation & Amortisation' },
    { code: '710200', name: 'Motor Vehicle - Depreciation', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '710000', level: 2, subClass: 'Depreciation & Amortisation' },
    { code: '710300', name: 'Farm Equipment - Depreciation', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '710000', level: 2, subClass: 'Depreciation & Amortisation' },
    { code: '710400', name: 'Furniture & Fittings - Depreciation', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '710000', level: 2, subClass: 'Depreciation & Amortisation' },
    { code: '710500', name: 'Green House - Depreciation', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '710000', level: 2, subClass: 'Depreciation & Amortisation' },
    { code: '710600', name: 'Computer Hardware - Depreciation', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '710000', level: 2, subClass: 'Depreciation & Amortisation' },
    { code: '710700', name: 'Loose Tools - Depreciation', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '710000', level: 2, subClass: 'Depreciation & Amortisation' },
    { code: '710800', name: 'Farm Land - Depreciation', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '710000', level: 2, subClass: 'Depreciation & Amortisation' },
    { code: '710900', name: 'Farm Plant & Machinery - Depreciation', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '710000', level: 2, subClass: 'Depreciation & Amortisation' },

    // ─── FINANCE COSTS ───────────────────────────────────────────────────────
    { code: '720000', name: 'Finance Costs', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '700000', level: 1, subClass: 'Finance Cost' },
    { code: '720100', name: 'Bank Charges', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '720000', level: 2, subClass: 'Finance Cost' },
    { code: '720200', name: 'Mobile Money Charges', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '720000', level: 2, subClass: 'Finance Cost' },
    { code: '720300', name: 'Loan Interest Expense', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '720000', level: 2, subClass: 'Finance Cost' },
    { code: '720400', name: 'Interest on Leases', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '720000', level: 2, subClass: 'Finance Cost' },

    // ─── ACCOUNTING ADJUSTMENTS ───────────────────────────────────────────────
    { code: '730000', name: 'Accounting Adjustments', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '700000', level: 1, subClass: 'Accounting Adjustment' },
    { code: '730100', name: 'Exchange Difference - Forex Gains', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '730000', level: 2, subClass: 'Accounting Adjustment' },
    { code: '730200', name: 'Exchange Difference - Forex Loss', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '730000', level: 2, subClass: 'Accounting Adjustment' },
    { code: '730300', name: 'Rounding Difference', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '730000', level: 2, subClass: 'Accounting Adjustment' },
    { code: '730400', name: 'Invoice Misstatement', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '730000', level: 2, subClass: 'Accounting Adjustment' },

    // ─── INVENTORY WRITE-OFFS ─────────────────────────────────────────────────
    { code: '740000', name: 'Inventory Write-Offs', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '700000', level: 1, subClass: 'Accounting Adjustment' },
    { code: '740100', name: 'Damaged Inventory', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '740000', level: 2, subClass: 'Accounting Adjustment' },
    { code: '740200', name: 'Expired Inventory', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '740000', level: 2, subClass: 'Accounting Adjustment' },
    { code: '740300', name: 'Low Standard Inventory', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '740000', level: 2, subClass: 'Accounting Adjustment' },
    { code: '740400', name: 'Diseased Inventory', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '740000', level: 2, subClass: 'Accounting Adjustment' },
  ],
};
