import { AccountClass, AccountType } from '@prisma/client';
import type { CoaTemplate } from '../coa.types';

export const retailTemplate: CoaTemplate = {
  name: 'Retail Chart of Accounts',
  description: 'Standard IFRS-compliant chart of accounts for retail businesses',
  industry: 'retail',
  accounts: [
    // ── ASSETS ──────────────────────────────────────────────────────────────
    { code: '100000', name: 'ASSETS', class: AccountClass.ASSET, type: AccountType.OTHER, parentCode: null, level: 1, isControlAccount: true },

    // Current Assets
    { code: '110000', name: 'Current Assets', class: AccountClass.ASSET, type: AccountType.OTHER, parentCode: '100000', level: 2, isControlAccount: true },
    { code: '111000', name: 'Cash and Cash Equivalents', class: AccountClass.ASSET, type: AccountType.OTHER, parentCode: '110000', level: 3, isControlAccount: true },
    { code: '111100', name: 'Petty Cash', class: AccountClass.ASSET, type: AccountType.CASH, parentCode: '111000', level: 4 },
    { code: '111200', name: 'Main Bank Account', class: AccountClass.ASSET, type: AccountType.BANK, parentCode: '111000', level: 4, isBankAccount: true },
    { code: '111300', name: 'Merchant Account', class: AccountClass.ASSET, type: AccountType.BANK, parentCode: '111000', level: 4, isBankAccount: true },
    { code: '112000', name: 'Trade Receivables', class: AccountClass.ASSET, type: AccountType.RECEIVABLE, parentCode: '110000', level: 3, isControlAccount: true },
    { code: '112100', name: 'Accounts Receivable', class: AccountClass.ASSET, type: AccountType.RECEIVABLE, parentCode: '112000', level: 4 },
    { code: '112200', name: 'Allowance for Doubtful Debts', class: AccountClass.ASSET, type: AccountType.RECEIVABLE, parentCode: '112000', level: 4, description: 'Contra-asset (IFRS 9 expected credit loss provision)' },
    { code: '113000', name: 'Inventories', class: AccountClass.ASSET, type: AccountType.INVENTORY, parentCode: '110000', level: 3, isControlAccount: true },
    { code: '113100', name: 'Merchandise Inventory', class: AccountClass.ASSET, type: AccountType.INVENTORY, parentCode: '113000', level: 4 },
    { code: '113200', name: 'Goods in Transit', class: AccountClass.ASSET, type: AccountType.INVENTORY, parentCode: '113000', level: 4 },
    { code: '113300', name: 'Inventory Write-Down Reserve', class: AccountClass.ASSET, type: AccountType.INVENTORY, parentCode: '113000', level: 4, description: 'IAS 2 NRV write-down provision' },
    { code: '114000', name: 'Prepayments & Other Current Assets', class: AccountClass.ASSET, type: AccountType.OTHER, parentCode: '110000', level: 3 },
    { code: '114100', name: 'Prepaid Rent', class: AccountClass.ASSET, type: AccountType.OTHER, parentCode: '114000', level: 4 },
    { code: '114200', name: 'Prepaid Insurance', class: AccountClass.ASSET, type: AccountType.OTHER, parentCode: '114000', level: 4 },
    { code: '114300', name: 'Tax Refund Receivable', class: AccountClass.ASSET, type: AccountType.TAX_RECEIVABLE, parentCode: '114000', level: 4 },
    { code: '114400', name: 'Input VAT Recoverable', class: AccountClass.ASSET, type: AccountType.TAX_RECEIVABLE, parentCode: '114000', level: 4 },

    // Non-Current Assets
    { code: '120000', name: 'Non-Current Assets', class: AccountClass.ASSET, type: AccountType.OTHER, parentCode: '100000', level: 2, isControlAccount: true },
    { code: '121000', name: 'Property, Plant & Equipment', class: AccountClass.ASSET, type: AccountType.FIXED_ASSET, parentCode: '120000', level: 3, isControlAccount: true },
    { code: '121100', name: 'Leasehold Improvements — Cost', class: AccountClass.ASSET, type: AccountType.FIXED_ASSET, parentCode: '121000', level: 4 },
    { code: '121110', name: 'Leasehold Improvements — Accum. Depreciation', class: AccountClass.ASSET, type: AccountType.FIXED_ASSET, parentCode: '121100', level: 5 },
    { code: '121200', name: 'Fixtures & Fittings — Cost', class: AccountClass.ASSET, type: AccountType.FIXED_ASSET, parentCode: '121000', level: 4 },
    { code: '121210', name: 'Fixtures & Fittings — Accum. Depreciation', class: AccountClass.ASSET, type: AccountType.FIXED_ASSET, parentCode: '121200', level: 5 },
    { code: '121300', name: 'Point-of-Sale Equipment — Cost', class: AccountClass.ASSET, type: AccountType.FIXED_ASSET, parentCode: '121000', level: 4 },
    { code: '121310', name: 'Point-of-Sale Equipment — Accum. Depreciation', class: AccountClass.ASSET, type: AccountType.FIXED_ASSET, parentCode: '121300', level: 5 },
    { code: '121400', name: 'Office Equipment — Cost', class: AccountClass.ASSET, type: AccountType.FIXED_ASSET, parentCode: '121000', level: 4 },
    { code: '121410', name: 'Office Equipment — Accum. Depreciation', class: AccountClass.ASSET, type: AccountType.FIXED_ASSET, parentCode: '121400', level: 5 },
    { code: '121500', name: 'Motor Vehicles — Cost', class: AccountClass.ASSET, type: AccountType.FIXED_ASSET, parentCode: '121000', level: 4 },
    { code: '121510', name: 'Motor Vehicles — Accum. Depreciation', class: AccountClass.ASSET, type: AccountType.FIXED_ASSET, parentCode: '121500', level: 5 },
    { code: '122000', name: 'Right-of-Use Assets (IFRS 16)', class: AccountClass.ASSET, type: AccountType.RIGHT_OF_USE_ASSET, parentCode: '120000', level: 3 },
    { code: '122100', name: 'ROU Asset — Store Leases', class: AccountClass.ASSET, type: AccountType.RIGHT_OF_USE_ASSET, parentCode: '122000', level: 4 },
    { code: '122200', name: 'ROU Asset — Warehouse Leases', class: AccountClass.ASSET, type: AccountType.RIGHT_OF_USE_ASSET, parentCode: '122000', level: 4 },
    { code: '123000', name: 'Intangible Assets', class: AccountClass.ASSET, type: AccountType.INTANGIBLE, parentCode: '120000', level: 3 },
    { code: '123100', name: 'Software & Licences — Cost', class: AccountClass.ASSET, type: AccountType.INTANGIBLE, parentCode: '123000', level: 4 },
    { code: '123110', name: 'Software & Licences — Accum. Amortisation', class: AccountClass.ASSET, type: AccountType.INTANGIBLE, parentCode: '123100', level: 5 },

    // ── LIABILITIES ──────────────────────────────────────────────────────────
    { code: '200000', name: 'LIABILITIES', class: AccountClass.LIABILITY, type: AccountType.OTHER, parentCode: null, level: 1, isControlAccount: true },

    { code: '210000', name: 'Current Liabilities', class: AccountClass.LIABILITY, type: AccountType.OTHER, parentCode: '200000', level: 2, isControlAccount: true },
    { code: '211000', name: 'Trade Payables', class: AccountClass.LIABILITY, type: AccountType.PAYABLE, parentCode: '210000', level: 3, isControlAccount: true },
    { code: '211100', name: 'Accounts Payable — Suppliers', class: AccountClass.LIABILITY, type: AccountType.PAYABLE, parentCode: '211000', level: 4 },
    { code: '212000', name: 'Accrued Liabilities', class: AccountClass.LIABILITY, type: AccountType.OTHER, parentCode: '210000', level: 3 },
    { code: '212100', name: 'Accrued Salaries', class: AccountClass.LIABILITY, type: AccountType.OTHER, parentCode: '212000', level: 4 },
    { code: '212200', name: 'Accrued Rent', class: AccountClass.LIABILITY, type: AccountType.OTHER, parentCode: '212000', level: 4 },
    { code: '212300', name: 'Accrued Utilities', class: AccountClass.LIABILITY, type: AccountType.OTHER, parentCode: '212000', level: 4 },
    { code: '213000', name: 'Tax Liabilities', class: AccountClass.LIABILITY, type: AccountType.TAX_PAYABLE, parentCode: '210000', level: 3 },
    { code: '213100', name: 'VAT / Sales Tax Payable', class: AccountClass.LIABILITY, type: AccountType.TAX_PAYABLE, parentCode: '213000', level: 4 },
    { code: '213200', name: 'Corporate Income Tax Payable', class: AccountClass.LIABILITY, type: AccountType.TAX_PAYABLE, parentCode: '213000', level: 4 },
    { code: '213300', name: 'PAYE Payable', class: AccountClass.LIABILITY, type: AccountType.TAX_PAYABLE, parentCode: '213000', level: 4 },
    { code: '213400', name: 'Social Security Payable', class: AccountClass.LIABILITY, type: AccountType.TAX_PAYABLE, parentCode: '213000', level: 4 },
    { code: '214000', name: 'Short-Term Borrowings', class: AccountClass.LIABILITY, type: AccountType.OTHER, parentCode: '210000', level: 3 },
    { code: '214100', name: 'Bank Overdraft', class: AccountClass.LIABILITY, type: AccountType.OTHER, parentCode: '214000', level: 4 },
    { code: '214200', name: 'Current Portion of Long-Term Debt', class: AccountClass.LIABILITY, type: AccountType.OTHER, parentCode: '214000', level: 4 },
    { code: '215000', name: 'Lease Liabilities — Current (IFRS 16)', class: AccountClass.LIABILITY, type: AccountType.OTHER, parentCode: '210000', level: 3 },
    { code: '216000', name: 'Gift Cards & Customer Deposits', class: AccountClass.LIABILITY, type: AccountType.OTHER, parentCode: '210000', level: 3 },

    { code: '220000', name: 'Non-Current Liabilities', class: AccountClass.LIABILITY, type: AccountType.OTHER, parentCode: '200000', level: 2, isControlAccount: true },
    { code: '221000', name: 'Long-Term Borrowings', class: AccountClass.LIABILITY, type: AccountType.OTHER, parentCode: '220000', level: 3 },
    { code: '221100', name: 'Bank Loan', class: AccountClass.LIABILITY, type: AccountType.OTHER, parentCode: '221000', level: 4 },
    { code: '222000', name: 'Lease Liabilities — Non-Current (IFRS 16)', class: AccountClass.LIABILITY, type: AccountType.OTHER, parentCode: '220000', level: 3 },
    { code: '223000', name: 'Deferred Tax Liability', class: AccountClass.LIABILITY, type: AccountType.TAX_PAYABLE, parentCode: '220000', level: 3 },

    // ── EQUITY ───────────────────────────────────────────────────────────────
    { code: '300000', name: 'EQUITY', class: AccountClass.EQUITY, type: AccountType.EQUITY_ACCOUNT, parentCode: null, level: 1, isControlAccount: true },
    { code: '310000', name: 'Share Capital', class: AccountClass.EQUITY, type: AccountType.EQUITY_ACCOUNT, parentCode: '300000', level: 2 },
    { code: '310100', name: 'Ordinary Share Capital', class: AccountClass.EQUITY, type: AccountType.EQUITY_ACCOUNT, parentCode: '310000', level: 3 },
    { code: '320000', name: 'Retained Earnings', class: AccountClass.EQUITY, type: AccountType.EQUITY_ACCOUNT, parentCode: '300000', level: 2 },
    { code: '320100', name: 'Retained Earnings — Prior Years', class: AccountClass.EQUITY, type: AccountType.EQUITY_ACCOUNT, parentCode: '320000', level: 3 },
    { code: '320200', name: 'Profit / Loss — Current Year', class: AccountClass.EQUITY, type: AccountType.EQUITY_ACCOUNT, parentCode: '320000', level: 3 },
    { code: '330000', name: 'Other Reserves', class: AccountClass.EQUITY, type: AccountType.EQUITY_ACCOUNT, parentCode: '300000', level: 2 },
    { code: '330100', name: 'Foreign Currency Translation Reserve', class: AccountClass.EQUITY, type: AccountType.EQUITY_ACCOUNT, parentCode: '330000', level: 3 },

    // ── REVENUE ──────────────────────────────────────────────────────────────
    { code: '400000', name: 'REVENUE', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: null, level: 1, isControlAccount: true },
    { code: '410000', name: 'Sales Revenue', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '400000', level: 2 },
    { code: '410100', name: 'Product Sales — General', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 3 },
    { code: '410200', name: 'Online Sales', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 3 },
    { code: '410300', name: 'In-Store Sales', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 3 },
    { code: '410400', name: 'Wholesale Sales', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 3 },
    { code: '420000', name: 'Sales Returns & Allowances', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '400000', level: 2, description: 'Contra-revenue account' },
    { code: '420100', name: 'Sales Returns', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '420000', level: 3 },
    { code: '420200', name: 'Sales Discounts', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '420000', level: 3 },
    { code: '430000', name: 'Other Income', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '400000', level: 2 },
    { code: '430100', name: 'Rental Income', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '430000', level: 3 },
    { code: '430200', name: 'Interest Income', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '430000', level: 3 },
    { code: '430300', name: 'Gain on Disposal of Assets', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '430000', level: 3 },

    // ── COST OF SALES ─────────────────────────────────────────────────────────
    { code: '500000', name: 'COST OF SALES', class: AccountClass.EXPENSE, type: AccountType.COST_OF_SALES, parentCode: null, level: 1, isControlAccount: true },
    { code: '510000', name: 'Cost of Goods Sold', class: AccountClass.EXPENSE, type: AccountType.COST_OF_SALES, parentCode: '500000', level: 2 },
    { code: '510100', name: 'Merchandise Purchases', class: AccountClass.EXPENSE, type: AccountType.COST_OF_SALES, parentCode: '510000', level: 3 },
    { code: '510200', name: 'Freight Inwards', class: AccountClass.EXPENSE, type: AccountType.COST_OF_SALES, parentCode: '510000', level: 3 },
    { code: '510300', name: 'Purchase Returns & Allowances', class: AccountClass.EXPENSE, type: AccountType.COST_OF_SALES, parentCode: '510000', level: 3, description: 'Contra-COGS' },
    { code: '510400', name: 'Inventory Write-Offs', class: AccountClass.EXPENSE, type: AccountType.COST_OF_SALES, parentCode: '510000', level: 3 },
    { code: '510500', name: 'Shrinkage & Theft Losses', class: AccountClass.EXPENSE, type: AccountType.COST_OF_SALES, parentCode: '510000', level: 3 },
    { code: '520000', name: 'Warehousing & Distribution', class: AccountClass.EXPENSE, type: AccountType.COST_OF_SALES, parentCode: '500000', level: 2 },
    { code: '520100', name: 'Warehousing Costs', class: AccountClass.EXPENSE, type: AccountType.COST_OF_SALES, parentCode: '520000', level: 3 },
    { code: '520200', name: 'Delivery & Courier Costs', class: AccountClass.EXPENSE, type: AccountType.COST_OF_SALES, parentCode: '520000', level: 3 },

    // ── OPERATING EXPENSES ───────────────────────────────────────────────────
    { code: '600000', name: 'OPERATING EXPENSES', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: null, level: 1, isControlAccount: true },

    { code: '610000', name: 'Personnel Costs', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '600000', level: 2 },
    { code: '610100', name: 'Salaries & Wages', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '610000', level: 3 },
    { code: '610200', name: 'Employer Social Security Contributions', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '610000', level: 3 },
    { code: '610300', name: 'Staff Training & Development', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '610000', level: 3 },
    { code: '610400', name: 'Staff Uniforms', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '610000', level: 3 },

    { code: '620000', name: 'Occupancy Costs', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '600000', level: 2 },
    { code: '620100', name: 'Rent Expense', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '620000', level: 3 },
    { code: '620200', name: 'Rates & Municipal Charges', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '620000', level: 3 },
    { code: '620300', name: 'Electricity & Water', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '620000', level: 3 },
    { code: '620400', name: 'Security Services', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '620000', level: 3 },

    { code: '630000', name: 'Marketing & Advertising', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '600000', level: 2 },
    { code: '630100', name: 'Advertising Spend', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '630000', level: 3 },
    { code: '630200', name: 'Social Media & Digital Marketing', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '630000', level: 3 },
    { code: '630300', name: 'Promotions & Discounting Events', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '630000', level: 3 },

    { code: '640000', name: 'General & Administrative', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '600000', level: 2 },
    { code: '640100', name: 'Office Supplies', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '640000', level: 3 },
    { code: '640200', name: 'Telephone & Internet', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '640000', level: 3 },
    { code: '640300', name: 'Professional Fees (Audit/Legal)', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '640000', level: 3 },
    { code: '640400', name: 'Bank Charges', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '640000', level: 3 },
    { code: '640500', name: 'Insurance', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '640000', level: 3 },
    { code: '640600', name: 'Software Subscriptions', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '640000', level: 3 },

    { code: '650000', name: 'Depreciation & Amortisation', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '600000', level: 2 },
    { code: '650100', name: 'Depreciation — Fixtures & Fittings', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '650000', level: 3 },
    { code: '650200', name: 'Depreciation — POS Equipment', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '650000', level: 3 },
    { code: '650300', name: 'Depreciation — Motor Vehicles', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '650000', level: 3 },
    { code: '650400', name: 'Amortisation — ROU Assets', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '650000', level: 3, description: 'IFRS 16 ROU asset amortisation' },
    { code: '650500', name: 'Amortisation — Intangibles', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '650000', level: 3 },

    { code: '660000', name: 'Finance Costs', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '600000', level: 2 },
    { code: '660100', name: 'Loan Interest Expense', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '660000', level: 3 },
    { code: '660200', name: 'Lease Interest Expense (IFRS 16)', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '660000', level: 3 },
    { code: '660300', name: 'Foreign Exchange Loss', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '660000', level: 3 },

    { code: '670000', name: 'Income Tax Expense', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '600000', level: 2 },
    { code: '670100', name: 'Current Tax Expense', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '670000', level: 3 },
    { code: '670200', name: 'Deferred Tax Expense', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '670000', level: 3 },
  ],
};
