import { AccountClass, AccountType } from '@prisma/client';
import type { CoaTemplate } from '../coa.types';

export const technologyTemplate: CoaTemplate = {
  name: 'Technology / SaaS Chart of Accounts',
  description: 'IFRS-compliant chart of accounts for software, SaaS, and technology companies (IFRS 15 revenue recognition, IAS 38 R&D capitalisation)',
  industry: 'technology',
  accounts: [
    // ── ASSETS ──────────────────────────────────────────────────────────────
    { code: '100000', name: 'ASSETS', class: AccountClass.ASSET, type: AccountType.OTHER, parentCode: null, level: 1, isControlAccount: true },

    { code: '110000', name: 'Current Assets', class: AccountClass.ASSET, type: AccountType.OTHER, parentCode: '100000', level: 2, isControlAccount: true },
    { code: '111000', name: 'Cash and Cash Equivalents', class: AccountClass.ASSET, type: AccountType.OTHER, parentCode: '110000', level: 3, isControlAccount: true },
    { code: '111100', name: 'Petty Cash', class: AccountClass.ASSET, type: AccountType.CASH, parentCode: '111000', level: 4 },
    { code: '111200', name: 'Operating Bank Account', class: AccountClass.ASSET, type: AccountType.BANK, parentCode: '111000', level: 4, isBankAccount: true },
    { code: '111300', name: 'USD Bank Account', class: AccountClass.ASSET, type: AccountType.BANK, parentCode: '111000', level: 4, isBankAccount: true, currency: 'USD' },
    { code: '112000', name: 'Trade Receivables', class: AccountClass.ASSET, type: AccountType.RECEIVABLE, parentCode: '110000', level: 3, isControlAccount: true },
    { code: '112100', name: 'Accounts Receivable', class: AccountClass.ASSET, type: AccountType.RECEIVABLE, parentCode: '112000', level: 4 },
    { code: '112200', name: 'Allowance for Doubtful Debts', class: AccountClass.ASSET, type: AccountType.RECEIVABLE, parentCode: '112000', level: 4, description: 'IFRS 9 ECL provision' },
    { code: '112300', name: 'Contract Assets — Unbilled Revenue', class: AccountClass.ASSET, type: AccountType.RECEIVABLE, parentCode: '112000', level: 4, description: 'IFRS 15 — performance obligation satisfied, not yet invoiced' },
    { code: '113000', name: 'Prepayments & Other Current Assets', class: AccountClass.ASSET, type: AccountType.OTHER, parentCode: '110000', level: 3 },
    { code: '113100', name: 'Prepaid SaaS & Software Costs', class: AccountClass.ASSET, type: AccountType.OTHER, parentCode: '113000', level: 4 },
    { code: '113200', name: 'Prepaid Insurance', class: AccountClass.ASSET, type: AccountType.OTHER, parentCode: '113000', level: 4 },
    { code: '113300', name: 'Input VAT Recoverable', class: AccountClass.ASSET, type: AccountType.TAX_RECEIVABLE, parentCode: '113000', level: 4 },
    { code: '113400', name: 'Deferred Commission Assets (IFRS 15)', class: AccountClass.ASSET, type: AccountType.OTHER, parentCode: '113000', level: 4, description: 'Incremental costs of obtaining a contract' },

    { code: '120000', name: 'Non-Current Assets', class: AccountClass.ASSET, type: AccountType.OTHER, parentCode: '100000', level: 2, isControlAccount: true },
    { code: '121000', name: 'Property, Plant & Equipment', class: AccountClass.ASSET, type: AccountType.FIXED_ASSET, parentCode: '120000', level: 3, isControlAccount: true },
    { code: '121100', name: 'Servers & Data Centre Equipment — Cost', class: AccountClass.ASSET, type: AccountType.FIXED_ASSET, parentCode: '121000', level: 4 },
    { code: '121110', name: 'Servers & Data Centre Equipment — Accum. Dep.', class: AccountClass.ASSET, type: AccountType.FIXED_ASSET, parentCode: '121100', level: 5 },
    { code: '121200', name: 'Computer Hardware — Cost', class: AccountClass.ASSET, type: AccountType.FIXED_ASSET, parentCode: '121000', level: 4 },
    { code: '121210', name: 'Computer Hardware — Accum. Depreciation', class: AccountClass.ASSET, type: AccountType.FIXED_ASSET, parentCode: '121200', level: 5 },
    { code: '121300', name: 'Office Furniture & Equipment — Cost', class: AccountClass.ASSET, type: AccountType.FIXED_ASSET, parentCode: '121000', level: 4 },
    { code: '121310', name: 'Office Furniture & Equipment — Accum. Dep.', class: AccountClass.ASSET, type: AccountType.FIXED_ASSET, parentCode: '121300', level: 5 },
    { code: '122000', name: 'Right-of-Use Assets (IFRS 16)', class: AccountClass.ASSET, type: AccountType.RIGHT_OF_USE_ASSET, parentCode: '120000', level: 3 },
    { code: '122100', name: 'ROU Asset — Office Leases', class: AccountClass.ASSET, type: AccountType.RIGHT_OF_USE_ASSET, parentCode: '122000', level: 4 },
    { code: '122200', name: 'ROU Asset — Data Centre Co-location', class: AccountClass.ASSET, type: AccountType.RIGHT_OF_USE_ASSET, parentCode: '122000', level: 4 },
    { code: '123000', name: 'Intangible Assets', class: AccountClass.ASSET, type: AccountType.INTANGIBLE, parentCode: '120000', level: 3 },
    { code: '123100', name: 'Capitalised Software Development Costs — Cost', class: AccountClass.ASSET, type: AccountType.INTANGIBLE, parentCode: '123000', level: 4, description: 'IAS 38 — development phase costs only; research costs expensed' },
    { code: '123110', name: 'Capitalised Software Dev. — Accum. Amortisation', class: AccountClass.ASSET, type: AccountType.INTANGIBLE, parentCode: '123100', level: 5 },
    { code: '123200', name: 'Acquired Software & Licences — Cost', class: AccountClass.ASSET, type: AccountType.INTANGIBLE, parentCode: '123000', level: 4 },
    { code: '123210', name: 'Acquired Software & Licences — Accum. Amort.', class: AccountClass.ASSET, type: AccountType.INTANGIBLE, parentCode: '123200', level: 5 },
    { code: '123300', name: 'Patents & IP — Cost', class: AccountClass.ASSET, type: AccountType.INTANGIBLE, parentCode: '123000', level: 4 },
    { code: '123310', name: 'Patents & IP — Accum. Amortisation', class: AccountClass.ASSET, type: AccountType.INTANGIBLE, parentCode: '123300', level: 5 },
    { code: '123400', name: 'Goodwill', class: AccountClass.ASSET, type: AccountType.INTANGIBLE, parentCode: '123000', level: 4, description: 'IFRS 3 — impairment tested annually; not amortised' },

    // ── LIABILITIES ──────────────────────────────────────────────────────────
    { code: '200000', name: 'LIABILITIES', class: AccountClass.LIABILITY, type: AccountType.OTHER, parentCode: null, level: 1, isControlAccount: true },

    { code: '210000', name: 'Current Liabilities', class: AccountClass.LIABILITY, type: AccountType.OTHER, parentCode: '200000', level: 2, isControlAccount: true },
    { code: '211000', name: 'Trade Payables', class: AccountClass.LIABILITY, type: AccountType.PAYABLE, parentCode: '210000', level: 3, isControlAccount: true },
    { code: '211100', name: 'Accounts Payable', class: AccountClass.LIABILITY, type: AccountType.PAYABLE, parentCode: '211000', level: 4 },
    { code: '212000', name: 'Accrued Liabilities', class: AccountClass.LIABILITY, type: AccountType.OTHER, parentCode: '210000', level: 3 },
    { code: '212100', name: 'Accrued Salaries & Bonuses', class: AccountClass.LIABILITY, type: AccountType.OTHER, parentCode: '212000', level: 4 },
    { code: '212200', name: 'Accrued Cloud Infrastructure Costs', class: AccountClass.LIABILITY, type: AccountType.OTHER, parentCode: '212000', level: 4 },
    { code: '213000', name: 'Contract Liabilities — Deferred Revenue', class: AccountClass.LIABILITY, type: AccountType.OTHER, parentCode: '210000', level: 3, description: 'IFRS 15 — subscriptions billed in advance; recognised as service delivered' },
    { code: '213100', name: 'Deferred Revenue — Annual Subscriptions', class: AccountClass.LIABILITY, type: AccountType.OTHER, parentCode: '213000', level: 4 },
    { code: '213200', name: 'Deferred Revenue — Multi-Year Contracts', class: AccountClass.LIABILITY, type: AccountType.OTHER, parentCode: '213000', level: 4 },
    { code: '214000', name: 'Tax Liabilities', class: AccountClass.LIABILITY, type: AccountType.TAX_PAYABLE, parentCode: '210000', level: 3 },
    { code: '214100', name: 'VAT Payable', class: AccountClass.LIABILITY, type: AccountType.TAX_PAYABLE, parentCode: '214000', level: 4 },
    { code: '214200', name: 'Corporate Tax Payable', class: AccountClass.LIABILITY, type: AccountType.TAX_PAYABLE, parentCode: '214000', level: 4 },
    { code: '214300', name: 'PAYE & Social Security Payable', class: AccountClass.LIABILITY, type: AccountType.TAX_PAYABLE, parentCode: '214000', level: 4 },
    { code: '215000', name: 'Lease Liabilities — Current (IFRS 16)', class: AccountClass.LIABILITY, type: AccountType.OTHER, parentCode: '210000', level: 3 },

    { code: '220000', name: 'Non-Current Liabilities', class: AccountClass.LIABILITY, type: AccountType.OTHER, parentCode: '200000', level: 2, isControlAccount: true },
    { code: '221000', name: 'Long-Term Debt', class: AccountClass.LIABILITY, type: AccountType.OTHER, parentCode: '220000', level: 3 },
    { code: '221100', name: 'Bank Loan', class: AccountClass.LIABILITY, type: AccountType.OTHER, parentCode: '221000', level: 4 },
    { code: '221200', name: 'Convertible Notes', class: AccountClass.LIABILITY, type: AccountType.OTHER, parentCode: '221000', level: 4 },
    { code: '222000', name: 'Lease Liabilities — Non-Current (IFRS 16)', class: AccountClass.LIABILITY, type: AccountType.OTHER, parentCode: '220000', level: 3 },
    { code: '223000', name: 'Deferred Tax Liability', class: AccountClass.LIABILITY, type: AccountType.TAX_PAYABLE, parentCode: '220000', level: 3 },
    { code: '224000', name: 'Deferred Revenue — Non-Current', class: AccountClass.LIABILITY, type: AccountType.OTHER, parentCode: '220000', level: 3, description: 'Multi-year deferred revenue (IFRS 15)' },

    // ── EQUITY ───────────────────────────────────────────────────────────────
    { code: '300000', name: 'EQUITY', class: AccountClass.EQUITY, type: AccountType.EQUITY_ACCOUNT, parentCode: null, level: 1, isControlAccount: true },
    { code: '310000', name: 'Share Capital', class: AccountClass.EQUITY, type: AccountType.EQUITY_ACCOUNT, parentCode: '300000', level: 2 },
    { code: '310100', name: 'Ordinary Share Capital', class: AccountClass.EQUITY, type: AccountType.EQUITY_ACCOUNT, parentCode: '310000', level: 3 },
    { code: '310200', name: 'Share Premium', class: AccountClass.EQUITY, type: AccountType.EQUITY_ACCOUNT, parentCode: '310000', level: 3 },
    { code: '310300', name: 'Preference Share Capital', class: AccountClass.EQUITY, type: AccountType.EQUITY_ACCOUNT, parentCode: '310000', level: 3 },
    { code: '320000', name: 'Retained Earnings / Accumulated Deficit', class: AccountClass.EQUITY, type: AccountType.EQUITY_ACCOUNT, parentCode: '300000', level: 2 },
    { code: '320100', name: 'Retained Earnings — Prior Years', class: AccountClass.EQUITY, type: AccountType.EQUITY_ACCOUNT, parentCode: '320000', level: 3 },
    { code: '320200', name: 'Profit / Loss — Current Year', class: AccountClass.EQUITY, type: AccountType.EQUITY_ACCOUNT, parentCode: '320000', level: 3 },
    { code: '330000', name: 'Other Reserves', class: AccountClass.EQUITY, type: AccountType.EQUITY_ACCOUNT, parentCode: '300000', level: 2 },
    { code: '330100', name: 'Share-Based Payment Reserve (IFRS 2)', class: AccountClass.EQUITY, type: AccountType.EQUITY_ACCOUNT, parentCode: '330000', level: 3 },
    { code: '330200', name: 'Foreign Currency Translation Reserve', class: AccountClass.EQUITY, type: AccountType.EQUITY_ACCOUNT, parentCode: '330000', level: 3 },

    // ── REVENUE ──────────────────────────────────────────────────────────────
    { code: '400000', name: 'REVENUE', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: null, level: 1, isControlAccount: true },
    { code: '410000', name: 'Subscription Revenue (IFRS 15)', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '400000', level: 2 },
    { code: '410100', name: 'SaaS — Monthly Recurring Revenue', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 3 },
    { code: '410200', name: 'SaaS — Annual Subscriptions', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 3 },
    { code: '410300', name: 'SaaS — Enterprise Licences', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '410000', level: 3 },
    { code: '420000', name: 'Professional Services Revenue', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '400000', level: 2 },
    { code: '420100', name: 'Implementation & Onboarding Fees', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '420000', level: 3 },
    { code: '420200', name: 'Consulting & Customisation', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '420000', level: 3 },
    { code: '420300', name: 'Training Fees', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '420000', level: 3 },
    { code: '430000', name: 'Other Revenue', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '400000', level: 2 },
    { code: '430100', name: 'API Usage / Overage Fees', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '430000', level: 3 },
    { code: '430200', name: 'Marketplace / App Store Revenue', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '430000', level: 3 },
    { code: '430300', name: 'Interest Income', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '430000', level: 3 },
    { code: '430400', name: 'Gain on Disposal of Assets', class: AccountClass.REVENUE, type: AccountType.REVENUE_ACCOUNT, parentCode: '430000', level: 3 },

    // ── COST OF REVENUE ───────────────────────────────────────────────────────
    { code: '500000', name: 'COST OF REVENUE', class: AccountClass.EXPENSE, type: AccountType.COST_OF_SALES, parentCode: null, level: 1, isControlAccount: true },
    { code: '510000', name: 'Infrastructure & Hosting', class: AccountClass.EXPENSE, type: AccountType.COST_OF_SALES, parentCode: '500000', level: 2 },
    { code: '510100', name: 'Cloud Hosting (AWS / GCP / Azure)', class: AccountClass.EXPENSE, type: AccountType.COST_OF_SALES, parentCode: '510000', level: 3 },
    { code: '510200', name: 'CDN & Bandwidth Costs', class: AccountClass.EXPENSE, type: AccountType.COST_OF_SALES, parentCode: '510000', level: 3 },
    { code: '510300', name: 'Database & Storage Costs', class: AccountClass.EXPENSE, type: AccountType.COST_OF_SALES, parentCode: '510000', level: 3 },
    { code: '520000', name: 'Direct Labour — Engineering', class: AccountClass.EXPENSE, type: AccountType.COST_OF_SALES, parentCode: '500000', level: 2 },
    { code: '520100', name: 'Customer Success & Support Staff', class: AccountClass.EXPENSE, type: AccountType.COST_OF_SALES, parentCode: '520000', level: 3 },
    { code: '520200', name: 'DevOps & Site Reliability Staff', class: AccountClass.EXPENSE, type: AccountType.COST_OF_SALES, parentCode: '520000', level: 3 },
    { code: '530000', name: 'Third-Party SaaS & API Costs', class: AccountClass.EXPENSE, type: AccountType.COST_OF_SALES, parentCode: '500000', level: 2 },
    { code: '530100', name: 'Third-Party API Fees', class: AccountClass.EXPENSE, type: AccountType.COST_OF_SALES, parentCode: '530000', level: 3 },
    { code: '530200', name: 'Payment Processing Fees', class: AccountClass.EXPENSE, type: AccountType.COST_OF_SALES, parentCode: '530000', level: 3 },

    // ── OPERATING EXPENSES ───────────────────────────────────────────────────
    { code: '600000', name: 'OPERATING EXPENSES', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: null, level: 1, isControlAccount: true },

    { code: '610000', name: 'Research & Development', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '600000', level: 2, description: 'IAS 38 — research phase costs expensed; development phase may be capitalised' },
    { code: '610100', name: 'Engineering Salaries (R&D)', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '610000', level: 3 },
    { code: '610200', name: 'Product & Design Salaries', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '610000', level: 3 },
    { code: '610300', name: 'R&D Software Tools & Licences', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '610000', level: 3 },
    { code: '610400', name: 'Share-Based Compensation — Engineering (IFRS 2)', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '610000', level: 3 },

    { code: '620000', name: 'Sales & Marketing', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '600000', level: 2 },
    { code: '620100', name: 'Sales Staff Salaries', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '620000', level: 3 },
    { code: '620200', name: 'Sales Commissions (Amortised per IFRS 15)', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '620000', level: 3 },
    { code: '620300', name: 'Digital Marketing & Paid Ads', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '620000', level: 3 },
    { code: '620400', name: 'Events & Conferences', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '620000', level: 3 },
    { code: '620500', name: 'Content Marketing & SEO', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '620000', level: 3 },

    { code: '630000', name: 'General & Administrative', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '600000', level: 2 },
    { code: '630100', name: 'G&A Salaries', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '630000', level: 3 },
    { code: '630200', name: 'Office Rent & Facilities', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '630000', level: 3 },
    { code: '630300', name: 'Legal & Compliance Fees', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '630000', level: 3 },
    { code: '630400', name: 'Audit & Accounting Fees', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '630000', level: 3 },
    { code: '630500', name: 'Insurance', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '630000', level: 3 },
    { code: '630600', name: 'Bank Charges', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '630000', level: 3 },
    { code: '630700', name: 'Travel & Expenses', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '630000', level: 3 },
    { code: '630800', name: 'Share-Based Compensation — G&A (IFRS 2)', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '630000', level: 3 },

    { code: '640000', name: 'Depreciation & Amortisation', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '600000', level: 2 },
    { code: '640100', name: 'Depreciation — Hardware', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '640000', level: 3 },
    { code: '640200', name: 'Amortisation — Capitalised Dev. Costs', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '640000', level: 3 },
    { code: '640300', name: 'Amortisation — ROU Assets (IFRS 16)', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '640000', level: 3 },
    { code: '640400', name: 'Amortisation — Acquired Intangibles', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '640000', level: 3 },

    { code: '650000', name: 'Finance Costs', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '600000', level: 2 },
    { code: '650100', name: 'Loan & Note Interest Expense', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '650000', level: 3 },
    { code: '650200', name: 'Lease Interest — IFRS 16', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '650000', level: 3 },
    { code: '650300', name: 'Foreign Exchange Loss', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '650000', level: 3 },

    { code: '660000', name: 'Income Tax Expense', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '600000', level: 2 },
    { code: '660100', name: 'Current Tax Expense', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '660000', level: 3 },
    { code: '660200', name: 'Deferred Tax Expense', class: AccountClass.EXPENSE, type: AccountType.EXPENSE_ACCOUNT, parentCode: '660000', level: 3 },
  ],
};
