-- ============================================================
-- AP Enhancement Migration  —  SUPERSEDED, DO NOT RUN
-- ============================================================
-- This file used the wrong convention (snake_case columns + UUID types).
-- Prisma maps every field to a quoted camelCase TEXT column, so the table and
-- column DDL below failed against the live schema (e.g. "foreign key ... uuid
-- and text are incompatible"), and its enum step targeted a non-existent type
-- name ("approval_entity_type" instead of "ApprovalEntityType").
--
-- Each part has been replaced by a correct, idempotent migration that matches
-- the Prisma schema exactly. Run those instead:
--
--   1. WHT columns on suppliers (whtRate, whtClassification)
--        -> fix_column_naming_migration.sql
--   2. supplier_payments table
--        -> fix_missing_tables_migration.sql
--   3. supplier_credit_notes table
--        -> fix_missing_tables_migration.sql
--   4. ApprovalEntityType += 'SUPPLIER_INVOICE'
--        -> fix_approval_enum_migration.sql
--   5. WHT Payable account seeding
--        -> now provided automatically by the chart-of-accounts templates
--           seeded on organisation creation (coa.service.ts / organisations.service.ts)
--
-- All three fix migrations have already been applied to the Neon database.
-- This file is retained only for historical reference.
-- ============================================================
