-- ============================================================
-- Fixed Assets Enhancements Migration (IAS 16/36)  —  SUPERSEDED, DO NOT RUN
-- ============================================================
-- This file used the wrong convention (snake_case columns + UUID types).
-- Prisma maps every field to a quoted camelCase TEXT column, so the columns it
-- added were unreadable by the ORM (prisma.fixedAsset/assetCategory.findMany()
-- failed with "column ... does not exist") and the table DDL failed on
-- incompatible uuid/text foreign keys.
--
-- Each part has been replaced by a correct, idempotent migration that matches
-- the Prisma schema exactly. Run those instead:
--
--   1. fixed_assets.revaluationSurplusRemaining / revaluationReserveAccountId
--        -> fix_column_naming_migration.sql  (renames the snake_case columns,
--           also adds the missing fixed_assets.reducingBalanceRate)
--   2. asset_categories.retainedEarningsAccountId
--        -> fix_column_naming_migration.sql  (also adds the missing
--           asset_categories.gainLossOnDisposalAccountId)
--   3. asset_impairment_reversals table
--        -> fix_missing_tables_migration.sql
--
-- Features 1 (proration) and 2 (depreciation schedule) were pure service-layer
-- changes and needed no DDL.
--
-- Both fix migrations have already been applied to the Neon database.
-- This file is retained only for historical reference.
-- ============================================================
